version: '3.8'

volumes:
  mysql_data: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db_data
  static_data:  # Add a volume for static files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/static

networks:
  askbot_network:
    driver: bridge

services:
  db:
    image: mysql
    container_name: mysql_askbot
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: askbot_db
      MYSQL_USER: askbot_user
      MYSQL_PASSWORD: askbot_pass
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      askbot_network:
        aliases:
          - db.localhost
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: askbot_service
    command: bash -c "cd /app/askbot && /app/askbot/start.sh && gunicorn wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_data:/app/askbot/static  # Ensure this is where collectstatic outputs
    expose:
      - 8000
    depends_on:   
      db:
        condition: service_healthy
    networks:
      - askbot_network

  nginx:
    build: ./nginx
    volumes:
      - static_data:/home/app/web/staticfiles  # Ensure this matches where nginx looks for static files
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - askbot_network
